
ARG MYSQL_VERSION
ARG MYSQL_ROOT_PASSWORD
FROM mysql:${MYSQL_VERSION}

RUN echo "=================================================" \
    && echo "PASSWORD=$MYSQL_ROOT_PASSWORD" \
    && echo "=============================================="
ENV MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}